### ISSUE TITLE
[wallet] balance update

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#102]
## Feature / Issue
As a user I want to see my wallet balance up to date. We need to find out a way to keep balance in actual state. 

## Acceptance criteria
User is able to update balance manually and/or balance is updated by some triggers to improve UX.

## Additional information
We can't know if balance is updated before we fetch current balance, but we can update balance when, for example, user open wallet list screen.

Do we have an event-driven UI?
A) Should balance updated dynamically on any screen which displays wallet balance (dashboard, wallet)?
or
B) Should balance only update when a screen is redrawing, e.g. when user opens a screen with balance?

**Comment by florianlenz** [comment]
@seland We will att the tx queue in 0.3.2. Your wallet address should change after an successful transaction. It's impossible for you to know when it is successful. Pangea lib's will emit an event in the future when an TX succeed. Since a successful TX mean that your wallet balance should have changed you can updated it then.

**Comment by seland** [comment]
@florianlenz So, we will get event about all operations with the wallet, right? Not only ones initiated from our side? 
What do you think if we do an update every time wallet list screen is opened just for 0.3.1?

**Comment by seland** [comment]
Pull to refresh implemented on 0.5.x versions.
