### ISSUE TITLE
Language edit suggestions

### ISSUE THREAD

**Issue by infinitechaos** [Bit-Nation/BITNATION-Pangea-mobile#274]
These are just a few simple language edits I encountered in the current release of the app.

The language I've included below each screenshot contains my suggestions in quotations.

![capture _2018-03-03-00-12-25](https://user-images.githubusercontent.com/8084414/37227113-f6a0f1d8-2390-11e8-8dc5-fde53f59bf06.png)

The commas in all three paragraphs here can be removed.

![capture _2018-03-03-00-10-16](https://user-images.githubusercontent.com/8084414/37227132-08c1c8f6-2391-11e8-90c4-cc7ed3bf5e87.png)

Final paragraph: "Write the words on paper in order. Store the paper in a very safe place. If your device is lost, stolen, broken, or upgraded you must have this key to restore or unlock your wallet."

![capture _2018-03-03-00-10-00](https://user-images.githubusercontent.com/8084414/37227374-ee30b2da-2391-11e8-80ba-e3bbf676eae3.png)

First paragraph: "You need an Ethereum wallet for payments, creating Nations, and other useful services."

Second paragraph: "You can restore your wallet if you lose or change your phone. You will need your private key to restore your wallet."

![capture _2018-03-03-00-15-58](https://user-images.githubusercontent.com/8084414/37227509-5efcc2ec-2392-11e8-8d70-2ae9dcf69a2f.png)

"Become a World Citizen

Bitnation is a decentralized, open-source movement powered by Bitcoin 2.0 technology. Bitnation aims to facilitate a peer-to-peer voluntary governance system to compete with the prevailing top-down, one-size-fits-all, geographical apartheid Nation State model wherein your quality of life is arbitrarily defined by where you were born."

![capture _2018-03-03-00-01-16](https://user-images.githubusercontent.com/8084414/37228019-106b24dc-2394-11e8-88d2-7e7712297932.png)

"To secure your wallet you first need a private key.

You must write down your private key on paper. This process only takes a few minutes.

If you change your phone the only way to recover your wallet is by entering your private key!

Your private key protects everything in Bitnation so save your written private key in a safe place."

![capture _2018-03-03-00-11-21](https://user-images.githubusercontent.com/8084414/37228142-6b85ad74-2394-11e8-8815-50a47ecf2c78.png)

Pop up box: "Good work! Now write down the next group of 12 words."

![capture _2018-03-03-00-15-26](https://user-images.githubusercontent.com/8084414/37228188-a59bf66c-2394-11e8-9665-3243a08f240c.png)

"Congratulations! You correctly entered your private key.

Now put your paper with your private key in a safe place."

**Comment by mimetic** [comment]
Some good fixes! Here are my notes:

Do not make comma changes in the first two screens. The commas are there for clarity — to break up the text. The commas also help show the content breaks in the sentences for the benefit non-English speakers. So, while some are not necessarily required for standard written English, they do make the text easier to understand.

**Wallet: Create Wallet:**
Make the text changes, as follows:
First paragraph: "You need an Ethereum wallet to make payments, to create nations, and to use other useful services."

Second paragraph: "You can restore your wallet if you lose or change your phone. You will need your private key to restore your wallet."

**Profile**
"Become a World Citizen
Bitnation is a decentralized, open-source movement powered by blockchain technology. Bitnation offers a peer-to-peer voluntary governance system to compete with the prevailing top-down, one-size-fits-all, geographical apartheid Nation State model wherein your quality of life is arbitrarily defined by where you were born."

**Create Wallet**
( note: the standard English typesetting is : _"private key."_ not _"private key"._ 
( However, it can look strange with names, since it is really intended for speech. )
( I am using commas for clarity, although I understand why someone else might wish to remove them. )

To secure your wallet you first need a "private key."
You must write down your private key on paper. This process only takes a few minutes.
If you change your phone, the only way to recover your wallet is by entering your private key!
Your private key protects everything in Bitnation, so save your written private key in a safe place."

**Create Wallet Popup Box**
Pop up box: "Good work! Now, write down the next group of 12 words."

**Verify Private Key**

Congratulations! You correctly entered your private key.
Now, put your paper with your private key in a safe place."


-----
Thanks to @infinitechaos for catching so many mistakes! My only "disagreement" is about commas, and my reasoning is that I find my use of commas easier to understand, especially for a non-English speaker. However, if the commas are truly a problem, removing them is OK with me.

**Comment by albertoestarrona** [comment]
Solved in #298
