### ISSUE TITLE
Draft Nation shows up in the wrong list?

### ISSUE THREAD

**Issue by Mnuzz** [Bit-Nation/BITNATION-Pangea-mobile#314]
## Feature / Issue
When I create a "Draft Nation" (saving a nation before creating it fully), my draft nation shows up at the BOTTOM of the All Nations list. A more expected UI would be for it to be at the top of the "My Nations" list.

**Comment by seland** [comment]
@Mnuzz Did you set a name for that draft? All nations are sorted alphabetically, so if you specify a name for it, it should be placed as any other nation. However, for drafts without name, putting it at the top makes sense, but it's more a UX question. 
cc @mimetic

**Comment by Mnuzz** [comment]
Yeah name started with a Z so that make sense.

**Comment by mimetic** [comment]
@Mnuzz The current designs put Draft nations in with other nations in your list, alphabetically ordered. I feared that with very little screen space on small devices, a) the label was 50pt of space we needed, b) one might stack up drafts at the top, and user has to scroll past every time, c) Not so hard to find draft nations, esp. because the "My Nation" tab shows only your nations, reducing the number on the screen, solving an issue of finding scrolling to your nation in a long list.

**Comment by mimetic** [comment]
@Mnuzz Also, UI design shows an A-Z jump list on the right, but it has never been implemented. That would be useful when there are many, many nations.

**Comment by Mnuzz** [comment]
@mimetic Makes sense, I think it can be confusing for some first-time users though. Might be a lot of work to fix it sounds like.

**Comment by mimetic** [comment]
@Mnuzz it should not be possible to create a nation with no name.

**Comment by seland** [comment]
@mimetic I suggest to close that issue or to rename it into something more specific about what should be done, since we figured it out, that draft was shown in the correct place. What do you think?
