### ISSUE TITLE
[iOS] Dashboard does not show created/joined nations

### ISSUE THREAD

**Issue by TaelsMD** [Bit-Nation/BITNATION-Pangea-mobile#334]
Apple iPhone 8 Plus iOS 11.2.6
## Feature / Issue
> After restoring the wallet, even though when I click on a nation I joined I can see the message "You are a citizen of ...", the dashboard does not show which nations I had created/joined.
![img_1725](https://user-images.githubusercontent.com/36716878/38098595-e1c779a8-334e-11e8-8532-2170dc89c9ad.jpg)

**Comment by seland** [comment]
@TaelsMD It's expected behavior in a sense that activity logs are showing your activity on specific device. They are designed to let you keep track of what's happening inside the app and they are only stored locally. Does it make sense to you? 
In case you think it's important to have logs restored as well, I'll change the issue to feature suggestion.

**Comment by seland** [comment]
Closing the issue due to inactivity. Feel free to reopen it if you experience it again.
